### ISSUE TITLE
cmp sources ordering

### ISSUE THREAD

**Issue by horriblename** [NotAShelf/nvf#153]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### 🏷️ Feature Type

API Additions

### 🔖 Feature description

currently cmp sources are ordered alphabetically with no possibility of reordering. this means that the `buffer` source will always show up before `LSP` source in the cmp menu, which is kinda annoying.

### ✔️ Solution

we could probably slap another option on top of `autocomplet.sources` which uses a dag instead of attrset. But that'd be a pain to configure

might be worth using custom merge function to allow something like:
```nix
sources = {
  buffer = {name = "[Buffer]"; priority = 2;};
  nvim_lsp = {name = "[LSP]"; priority = 1;};
};
```

**Comment by NotAShelf** [comment]
sounds like a good idea, although I am not very sure how we'd go around doing it currently - I'll try to take a look

**Comment by Freewalkr** [comment]
Seems like it's not fixed in the mentioned PR. `nvim-cmp.sources` [is still `attrs (nullOr str)`](https://github.com/diniamo/nvf/blob/f672d3cdee3617ad1321808f51929b2d2dbb5133/modules/plugins/completion/nvim-cmp/nvim-cmp.nix#L100) (and [the module sets a value](https://github.com/diniamo/nvf/blob/f672d3cdee3617ad1321808f51929b2d2dbb5133/modules/plugins/completion/nvim-cmp/config.nix#L75-L79) by default without mkDefault).
